### PR TITLE
Minor script change

### PR DESCRIPTION
**Pull request by RandallPark**
Change:
35:55 Yeah, that is beautiful. Ease is at the universal language of Json. Excellent.

To:
35:55 Yeah, that is beautiful. Use it as the universal language of Json. Excellent.

### CODE REVIEW

**Comment by mikeckennedy** [comment]
Thanks @RandallPark Looks right to me. I'm happy to reopen and merge it. Why did you close it? (other than my inbox is packed full and I'm slow responding :) ).

**Comment by RandallPark** [comment]
I apologize. I'm still learning how to use git hub. Brand new to coding. A fan of your show. I thought I would check out what you have on Git Hub and got excited to find a little something I could do. I didn't even realize I closed the issue you. More awkward than an 8 year old learning to drive stick!

**Comment by mikeckennedy** [comment]
I think you can reopen it and then I'll merge it. Thanks and I appreciate your contributions to the content.

**Comment by mikeckennedy** [comment]
Oh, still not reopened. But I can't do it since you started it AFAIK. :) 

Screen Shot 2019-06-18 at 10 17 39 AM

**Comment by RandallPark** [comment]
Thank you for your valuable attention! It motivated me to find arrive at a conclusion. I decided to go with opening a new PR. Which gives me that one more step of familiarity with using Github. Super valuable. Thanks!

**Comment by mikeckennedy** [comment]
Of course, thanks for taking the time to make a change and improve the transcripts. I'll push the change to the server in a moment.

**Pull request closed without merging**
