### PR TITLE
Contribute episode 263

### PR DESCRIPTION
**Pull request by simkimsia**
seo for developers

@mikeckennedy Can you take a look? I paid out of my own pocket to have this transcribed. I made almost zero changes to the freelancer who did this

ref #178

### CODE REVIEW

**Comment by mikeckennedy** [comment]
Hi @simkimsia Thank you so much, wow! I really appreciate this. It looks like I need a little tweaking on format to import it into the website actually. The site understands:

```
0:00:58 KENNEDY: Welcome to Talk Python to Me, a ...

0:01:27 GREGORY: Good to be back. ...
```

But the format here is 

```
Michael Kennedy:	00:00:00	As developers and technologists,

Christian Medina:	00:01:29	That's right. 
```

Which is fine, but not parseable by the webapp. I'll write a script to make that happen here, but just FYI. 

Again, wow and thanks. :)

**Comment by simkimsia** [comment]
Copy on the different formatting

If there’s a next time, I’ll follow your format

Have a good one @mikeckennedy 😊

**Comment by mikeckennedy** [comment]
Works great, thanks again: https://talkpython.fm/episodes/transcript/263/seo-for-developers

**Comment by mikeckennedy** [comment]
> "Copy on the different formatting"

Thanks again, that's great. But not a big deal because I now have a few lines of python that moves between them.

**Comment by simkimsia** [comment]
Ok cool

**Comment by simkimsia** [comment]
@mikeckennedy it just occurred to me.. do you want to know the freelancer that helped me with this?

**Comment by mikeckennedy** [comment]
Yeah, sure, you can email the details over to `michael    att talkpython.fm`. Thanks.

**Comment by simkimsia** [comment]
> Yeah, sure, you can email the details over to `michael att talkpython.fm`. Thanks.

Sorry somehow I miss this previously. Emailed you

**Pull request merged**
