### PR TITLE
Episode 132

### PR DESCRIPTION
**Pull request by kevinwrightleft**
Here ya go.

### CODE REVIEW

**Comment by mikeckennedy** [comment]
Thank you @kevinwrightleft

**Comment by ptaiga** [comment]
Hi, guys!

I found a small inaccuracy in the text of episode 132. The sentence:
> "00:21:57 Michael Kennedy: I'm sure he's not going to have to look for a long time, but the average person." 
should apply to previous paragraph of Dan Bader. 

How should I do, to create an Issue or PR? Or is this comment enough? Or is it not so important :)

Thanks for the great talk!

**Comment by mikeckennedy** [comment]
Hi @ptaiga PRs are always welcome, thank you! :)

**Comment by kevinwrightleft** [comment]
Thanks for finding the issue @ptaiga <https://github.com/ptaiga> .
@mikeckennedy, I'm fixing this right now and  you will get a PR from me
shortly.

Later,
Kevin

**Pull request merged**
